version: "3"

volumes:
  redis-data:

services:
  redis:
    image: "redis:6.0.9"
    restart: "unless-stopped"
    volumes:
      - "redis-data:/data"
    command: redis-server --appendonly yes
  devbots:
    image: "registry.example.com/devbots/devbots:master"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - "redis"
    restart: "unless-stopped"
    environment:
      REDIS_URI: "redis://redis:6379/0"
    ports:
      - "14082:8080"
